"""Emit src/tables.rs, the constants that convert between base 2^32 and base 58^5.

The identities the tables satisfy are asserted in tests/tables.rs, so the output
is checked by the crate rather than trusted from here.
"""

import sys

R = 58 ** 5


def enc_table(binary_len, intermediate_len):
    """table[i][k] such that 2^(32*(binary_len-1-i)) == sum_k table[i][k] * R^(intermediate_len-1-k)"""
    rows = []
    for i in range(binary_len):
        value = 1 << (32 * (binary_len - 1 - i))
        row = []
        for k in range(intermediate_len - 1):
            place = R ** (intermediate_len - 2 - k)
            row.append(value // place)
            value %= place
        assert value == 0, "encode table row did not divide out"
        rows.append(row)
    return rows


def dec_table(binary_len, intermediate_len):
    """table[i][k] such that R^(intermediate_len-1-i) == sum_k table[i][k] * 2^(32*(binary_len-1-k))"""
    rows = []
    for i in range(intermediate_len):
        value = R ** (intermediate_len - 1 - i)
        row = []
        for k in range(binary_len):
            place = 1 << (32 * (binary_len - 1 - k))
            row.append(value // place)
            value %= place
        assert value == 0, "decode table row did not divide out"
        rows.append(row)
    return rows


def place_rows(max_words):
    """rows[k][j] such that 2^(32*k) == sum_j rows[k][j] * R^j, least significant first"""
    rows = []
    value = 1
    for _ in range(max_words):
        remaining, row = value, []
        while remaining:
            row.append(remaining % R)
            remaining //= R
        rows.append(row or [0])
        value <<= 32
    return rows


def limb_rows(max_limbs):
    """rows[k][j] such that R^k == sum_j rows[k][j] * 2^(32*j), least significant first"""
    rows = []
    value = 1
    for _ in range(max_limbs):
        remaining, row = value, []
        while remaining:
            row.append(remaining % (1 << 32))
            remaining >>= 32
        rows.append(row or [0])
        value *= R
    return rows


def render_rows(rows, kind, place, holds, note):
    """Rows laid end to end with an index, since each is about one wider than the last"""
    offsets, at = [], 0
    for row in rows:
        offsets.append(at)
        at += len(row)
    offsets.append(at)
    widest = max(len(row) for row in rows)

    return "\n".join(
        [
            f"/// {holds} the widest value this table converts occupies",
            "///",
            f"/// {note}",
            f"pub const {kind}_WIDTH: usize = {widest + 2};",
            "",
            f"/// Rows this table holds, which is as many places as the codec's limit reaches",
            f"pub const {kind}_ROWS: usize = {len(rows)};",
            "",
            f"/// Where each {place} begins in [`{kind}_VALUES`]",
            f"pub static {kind}_OFFSETS: [u32; {len(offsets)}] = [",
        ]
        + ["    " + " ".join(f"{v}," for v in offsets[at : at + 12]) for at in range(0, len(offsets), 12)]
        + [
            "];",
            "",
            "/// Every row's entries, one row after another",
            "///",
            "/// A static rather than a const: at this size a const would be copied in",
            "/// at every place it is read instead of being read where it sits.",
            f"pub static {kind}_VALUES: [u32; {offsets[-1]}] = [",
        ]
        + ["    " + " ".join(f"{v}," for v in [v for row in rows for v in row][at : at + 8])
           for at in range(0, offsets[-1], 8)]
        + ["];"]
    )


def render_places(rows):
    """The place values laid end to end, with an index saying where each row starts"""
    offsets, at = [], 0
    for row in rows:
        offsets.append(at)
        at += len(row)
    offsets.append(at)
    widest = max(len(row) for row in rows)

    lines = [
        "//! Place values for the variable length encoder, generated by tools/gen_tables.py",
        "//!",
        "//! Row `k` is 2^(32*k) written in base 58^5, least significant limb first, so",
        "//! that a word standing at that place contributes to the limbs by multiplying",
        "//! rather than by dividing the whole value down. The rows grow by about one",
        "//! limb each, so they are laid end to end and indexed rather than squared off.",
        "//!",
        "//! Each row is rebuilt from the power it stands for in tests/tables.rs.",
        "",
        f"/// Limbs the widest value this table converts occupies",
        f"///",
        f"/// A word standing at the highest place multiplies that place by up to 2^32,",
        f"/// which reaches two limbs past it, so the widest row is not the answer.",
        f"pub const PLACE_LIMBS: usize = {widest + 2};",
        "",
        f"/// Where each power's limbs begin in [`PLACE_VALUES`]",
        f"pub static PLACE_OFFSETS: [u32; {len(offsets)}] = [",
    ]
    for at in range(0, len(offsets), 12):
        lines.append("    " + " ".join(f"{v}," for v in offsets[at : at + 12]))
    lines.append("];")
    lines.append("")
    lines.append(f"/// Every row's limbs, one row after another")
    lines.append("///")
    lines.append("/// A static rather than a const: at this size a const would be copied in")
    lines.append("/// at every place it is read instead of being read where it sits.")
    lines.append(f"pub static PLACE_VALUES: [u32; {offsets[-1]}] = [")
    flat = [value for row in rows for value in row]
    for at in range(0, len(flat), 8):
        lines.append("    " + " ".join(f"{v}," for v in flat[at : at + 8]))
    lines.append("];")
    return "\n".join(lines)


def render(name, rows, outer, inner):
    lines = [f"pub const {name}: [[u32; {inner}]; {outer}] = ["]
    for row in rows:
        lines.append("    [")
        for at in range(0, len(row), 6):
            lines.append("        " + " ".join(f"{v}," for v in row[at : at + 6]))
        lines.append("    ],")
    lines.append("];")
    return "\n".join(lines)


def main():
    if "--place-values" in sys.argv:
        # one Solana packet, which is what MAX_VARIABLE_LEN stands at
        max_len = 1232
        max_words = max_len // 4 + (max_len % 4 > 0)
        max_chars = max_len * 138 // 100 + 2
        max_limbs = max_chars // 5 + (max_chars % 5 > 0)
        print("\n".join([
            "//! Place values for the variable length codec, generated by tools/gen_tables.py",
            "//!",
            "//! Going out, row `k` of the first table is 2^(32*k) written in base 58^5.",
            "//! Coming back, row `k` of the second is 58^(5*k) written in base 2^32. Either",
            "//! way a value's places are multiplied in rather than divided out, and the",
            "//! rows grow by about one entry each, so they are laid end to end and indexed",
            "//! rather than squared off.",
            "//!",
            "//! Every row is rebuilt from the power it stands for in tests/tables.rs.",
            "",
            render_rows(
                place_rows(max_words),
                "PLACE",
                "power of two",
                "Limbs",
                "A word standing at the highest place multiplies it by up to 2^32, which",
            ) + "\n",
            render_rows(
                limb_rows(max_limbs),
                "LIMB",
                "power of the limb base",
                "Words",
                "A limb standing at the highest place multiplies it by up to 58^5, which",
            ),
        ]))
        return
    parts = [
        "//! Constants converting between base 2^32 words and base 58^5 limbs",
        "//!",
        "//! Generated by tools/gen_tables.py. The identity each table satisfies is",
        "//! checked in tests/tables.rs, so nothing here has to be taken on faith.",
        "",
        render("ENCODE_32", enc_table(8, 9), 8, 8),
        "",
        render("ENCODE_64", enc_table(16, 18), 16, 17),
        "",
        render("DECODE_32", dec_table(8, 9), 9, 8),
        "",
        render("DECODE_64", dec_table(16, 18), 18, 16),
        "",
    ]
    print("\n".join(parts))


if __name__ == "__main__":
    main()
